# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Task
    url: docs/
    weight: 20
  - name: Contact
    url: contact/
    weight: 50
  - name: Starter Kit
    url: https://github.com/trec-biogen/starter-kit-2025
    weight: 50

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: TREC
    name: "TREC 2025"
    url: "https://trec.nist.gov/cfp.html"
    weight: 3
  - identifier: BioGen 2024
    name: "BioGen 2024"
    url: "https://dmice.ohsu.edu/trec-biogen/"
    weight: 2
  - identifier: TREC Biomedical Tracks
    name: "TREC Biomedical Tracks"
    url: "https://www.trec-cds.org/"
    weight: 2